language: node_js
node_js: "10"

cache: npm

script:
- if [ "$TRAVIS_BRANCH" = "master" ]; then
    npm test && npm run build;
  else
    npm test;
  fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  on:
    branch: master